//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using ChatBot.Model.Abstract;
using System.ComponentModel.DataAnnotations.Schema;

namespace ChatBot.Model.Models
{
    // PrdProducts

    [Table("OW_OVERVIEW_ECOMMERCE")]
    public partial class OverviewEcommerce : ApproveAuditable
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int OVERVIEW_ECOMMERCE_ID { get; set; }
        public string PROJECT_ID { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string ITEM_REVENUE { get; set; }

        public string PRODUCT_DETAIL_VIEWS { get; set; }

        public string QUANTITY_ADDED_TO_CART { get; set; }

        public string QUANTITY_CHECKED_OUT { get; set; }

        public string DIMENSIONS { get; set; }
        public string DOMAIN { get; set; }

        public string VERSION { get; set; }
        public int VERSION_INT { get; set; }

    }
}
