//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using ChatBot.Model.Abstract;
using System.ComponentModel.DataAnnotations.Schema;

namespace ChatBot.Model.Models
{
    // PrdProducts

    [Table("OW_OVERVIEW_ECOMMERCE")]
    public partial class OverviewEcommerce : ApproveAuditable
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int OVERVIEW_ECOMMERCE_ID { get; set; }


        public string PROJECT_ID { get; set; }


        public string SESSIONS { get; set; }
        public string PAGEVIEWS { get; set; }
        public string TIMEONPAGE { get; set; }

        public string TRANSACTIONREVENUE { get; set; }

        public string PRODUCTDETAILVIEWS { get; set; }
        public string PRODUCTADDSTOCART { get; set; }

        public string PRODUCTCHECKOUTS { get; set; }

        public string USERS { get; set; }

        public string NEWS_USERS { get; set; }
        public string DOMAIN { get; set; }

        public string VERSION { get; set; }
        public int VERSION_INT { get; set; }



    }
}
