//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using ChatBot.Model.Abstract;
using System.ComponentModel.DataAnnotations.Schema;

namespace ChatBot.Model.Models
{
    // PrdProducts

    [Table("OW_PAGE_BEHAVIOR_ECOMMERCE")]
    public partial class PageBehaviorEcommerce : ApproveAuditable
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int PAGE_BEHAVIOR_ECOMMERCE_ID { get; set; }
        public string PROJECT_ID { get; set; }
        public string PAGE_PATH { get; set; }
        public string PAGE_VIEW { get; set; }
        public string PAGE_VALUE { get; set; }

        public string TIME_ON_PAGE { get; set; }

        public string EXIT_RATE { get; set; }

        public string DIMENSIONS { get; set; }
        public string DOMAIN { get; set; }

        public int VERSION_INT { get; set; }

    }
}
