//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using ChatBot.Model.Abstract;
using System.ComponentModel.DataAnnotations.Schema;

namespace ChatBot.Model.Models
{
    // PrdProducts

    [Table("OW_TRAFFIC_SOURCE_ECOMMERCE")]
    public partial class TrafficSourcesEcommerce : ApproveAuditable
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int TRAFFIC_SOURCE_ECOMMERCE_ID { get; set; }

        public string PROJECT_ID { get; set; }

        public string SOURCE { get; set; }
        public string MEDIUM { get; set; }
        public string SESSIONS { get; set; }

        public string SESSIONDURATION { get; set; }

        public string PAGEVIEWS { get; set; }

        public string EXITS { get; set; }

        public string TRANSACTIONS { get; set; }
        public string TRANSACTIONREVENUE { get; set; }

        public string DOMAIN { get; set; }
        public string VERSION { get; set; }
        public int VERSION_INT { get; set; }

    }
}
